config/routes.rb
SchemeFinderApi::Application.routes.draw do
  apipie
  devise_for :users

  get '/pages/about', to: 'pages#about', as: :about

  scope module: 'backend' do
    resource  :dashboard
    resources :accounts
    resources :schemes do
      collection {
        get :unconfirmed
      }
    end

    resources :feedbacks do
      collection {
        get :unapproved
      }
      member {
        put :approve
      }
    end

    # csv import
    concern :importable do
      collection {
        get :import_form
        post :import
      }
    end

    namespace :import_via_csv, module: "import_via_csv", path: "import_via_csv" do
      resources :schemes, only: [] do
        concerns :importable
      end

      resources :objects, only: [:index, :show] do
        resources :import_errors, only: [:index]
      end
    end
    # END csv  import
  end

  namespace :api do
    namespace :v1 do
      scope defaults: { format: 'json' } do
        resources :schemes, only: [:index, :create, :show] do
          scope module: :schemes do
            resources :feedbacks, only: [:index, :create]
          end
        end
        resources :activities, only: [:index]
        resources :age_ranges, only: [:index]
        resources :company_sizes, only: [:index]
        resources :locations, only: [:index]
        resources :sectors, only: [:index]
        resources :audiences, only: [:index]
        resources :subjects, only: [:index]
      end
    end
  end

  root to: 'backend/dashboards#show'
end

app/controllers/backend/import_via_csv/base_controller.rb
module Backend::ImportViaCsv
  class BaseController < ::Backend::BaseController
    expose(:active_top_nav) { :import_via_csv }
    expose(:csv_import) { CsvImport.find(params[:object_id]) }
    expose(:csv_imports_type) {
      # specific type imports or all imports
      params[:type] || "CsvImport"
    }
  end
end

app/controllers/backend/import_via_csv/import_errors_controller.rb
module Backend::ImportViaCsv
  class ImportErrorsController < ::Backend::ImportViaCsv::BaseController
    expose(:import_errors) { csv_import.import_errors.page(params[:page]) }
  end
end

app/controllers/backend/import_via_csv/objects_controller.rb
module Backend
  module ImportViaCsv
    class ObjectsController < ::Backend::ImportViaCsv::BaseController
      expose(:csv_imports) { csv_imports_class.most_recent.includes(:import_errors).page(params[:page]) }
      expose(:csv_import) { CsvImport.find(params[:id]) }

      def index
      end

      def show
        respond_to do |format|
          # for updating result for asynchronous importing
          format.json do
            render json: {
              state: csv_import.state,
              saved_count: csv_import.saved_count,
              failed_count: csv_import.failed_count
            }, status: 200
          end
        end
      end

      private
      def csv_imports_class
        csv_imports_type.constantize
      end
    end
  end
end

app/controllers/backend/import_via_csv/schemes_controller.rb
module Backend::ImportViaCsv
  class SchemesController < ::Backend::BaseController
    expose(:active_top_nav) { "import_via_csv" }
    expose(:csv_import) { CsvImports::Scheme.new(csv_import_params) }
    expose(:csv_import_type) { "CsvImports::Scheme" }

    def import_form
      self.csv_import = CsvImports::Scheme.new
    end

    def import
      if csv_import.save
        csv_import.schedule_import

        redirect_to import_via_csv_objects_path(type: csv_import.type),
                    notice: "The import has been scheduled"
      else
        render :import_form
      end
    end

    private
    def csv_import_params
      params.require(:csv_import).permit(
        :file, :file_cache
      )
    end
  end
end

app/views/backend/import_via_csv/objects/_csv_import_results.html.slim
span.imported
  span.saved_count
    = csv_import.saved_count
  span
    ' &nbsp;imported,

= link_to import_via_csv_object_import_errors_path(csv_import) do
  span.failed_count
    =' csv_import.failed_count
  | failed

app/views/backend/import_via_csv/objects/index.html.slim
.container-fluid
  .row-fluid
    .span12
      h1
        = "#{csv_imports_type.underscore.parameterize.titleize} Log"

      - if csv_imports.any?
        table.table.csv-imports
          colgroup
            col width='150'
            col width='150'
            col width='*'
          thead
            tr
              th Uploaded at
              th Status
              th Output

          tbody
            - CsvImportDecorator.decorate_collection(csv_imports).each do |csv_import|
              tr
                td = csv_import.created_at
                td
                  - if csv_import.pending?
                    = spinner csv_import.status,
                              data: { url: csv_import.path_for_status_update }

                    span.hide Completed
                  - else
                    span = csv_import.status
                td.results
                  - if csv_import.completed?
                    span.final= render 'csv_import_results', csv_import: csv_import

                  - else
                    span.nothing = csv_import.output
                    span.final.hide= render 'csv_import_results', csv_import: csv_import
      - else
        h4.empty-text No imports logged yet.