config/routes.rb
SchemeFinderApi::Application.routes.draw do
  apipie
  devise_for :users

  get '/pages/about', to: 'pages#about', as: :about

  scope module: 'backend' do
    resource  :dashboard
    resources :accounts
    resources :schemes do
      collection {
        get :unconfirmed
      }
    end

    resources :feedbacks do
      collection {
        get :unapproved
      }
      member {
        put :approve
      }
    end

    # csv import
    concern :importable do
      collection {
        get :import_form
        post :import
      }
    end

    namespace :import_via_csv, module: "import_via_csv", path: "import_via_csv" do
      resources :schemes, only: [] do
        concerns :importable
      end

      resources :objects, only: [:index, :show] do
        resources :import_errors, only: [:index]
      end
    end
    # END csv  import
  end

  namespace :api do
    namespace :v1 do
      scope defaults: { format: 'json' } do
        resources :schemes, only: [:index, :create, :show] do
          scope module: :schemes do
            resources :feedbacks, only: [:index, :create]
          end
        end
        resources :activities, only: [:index]
        resources :age_ranges, only: [:index]
        resources :company_sizes, only: [:index]
        resources :locations, only: [:index]
        resources :sectors, only: [:index]
        resources :audiences, only: [:index]
        resources :subjects, only: [:index]
      end
    end
  end

  root to: 'backend/dashboards#show'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  def after_sign_in_path_for(resource)
    root_path
  end
end

app/helpers/application_helper.rb
# -*- coding: utf-8 -*-

module ApplicationHelper
  #   nav_item 'Foo', '/foo', 'controller_foo', 'controller_bar'
  #   nav_item 'Foo', '/foo', %w(controller_foo controller_bar)
  #   nav_item 'Foo', '/foo', 'controller_foo', controller_bar: ['edit', 'new']
  #   nav_item 'Foo', '/foo', controller_foo: 'index', controller_bar: ['edit', 'new']
  #   nav_item 'Foo', '/foo', controller_foo: 'index', controller_bar: ['edit', 'new']
  #   nav_item 'Foo', '/foo', active_top_nav: :foos
  def nav_item(name, url, activator = '', opts = {})
    if (activator.is_a?(String) && (request.path.start_with?(activator) || controller_name == activator.to_s)) ||
      (activator.is_a?(Regexp) && request.path =~ activator) ||
      (activator.is_a?(Hash) && defined?(active_top_nav) && active_by_specified_activator?(activator)) ||
      (activator.is_a?(Hash) && !defined?(active_top_nav) && active_by_specified_controller?(activator))
      opts.merge!({ class: 'active' })
    end

    content_tag :li, opts do
      link_to name, url
    end
  end

  def active_by_specified_activator?(activator)
    active_top_nav.to_s == activator[:active_top_nav].to_s
  end

  def active_by_specified_controller?(activator)
    controller_name.in?(activator) ||
    Array.wrap(activator[controller_name.to_sym]).include?(action_name)
  end

  def nav_element(text, url, wrapper_options = {})
    content_tag :li, wrapper_options do
      link_to text, url
    end
  end

  def l(item, options = {})
    if item
      I18n.l(item, options)
    end
  end

  def undecorated(object)
    if object.is_a? Draper::Decorator
      object.source
    else
      object
    end
  end

  def data_controller_name
    if controller.class.name
      controller.class.name.gsub("::", "_")
    else
      controller.to_s
    end
  end

  def object_link(object, path_proc, opts = {})
    opts[:for_empty] ||= "-"
    opts[:name_method] ||= "to_s"
    opts[:link_opts] ||= {}

    if object
      link_to object.public_send(opts[:name_method]),
              path_proc.call(object),
              opts[:link_opts]
    else
      opts[:for_empty]
    end
  end

  def links_for_collection(collection, path_proc, opts = {})
    collection.map do |object|
      object_link object, path_proc, opts
    end
  end

  def linked_names(collection, path_proc, opts = {})
    opts[:join_with] ||= ", "
    opts[:for_empty] ||= "-"
    links_for_collection(collection, path_proc, opts).join(opts[:join_with])
                                                     .html_safe.presence || opts[:for_empty]
  end

  def collection_list(collection, opts = {})
    opts[:for_empty] ||= "-"
    opts[:name_method] ||= "to_s"
    opts[:join_with] ||= ", "

    if collection && collection.any?
      collection.map do |member|
        member.public_send(opts[:name_method])
      end.join(opts[:join_with]).presence || opts[:for_empty]
    else
      opts[:for_empty]
    end
  end

  def site_url(site)
    if (url = site).present?
      if url.starts_with?("http")
        url
      else
        "http://#{url}"
      end
    end
  end

  def site_link(site)
    link_to site, site_url(site)
  end

  def confirmation_icon(value)
    if value
      content_tag(:span, '✓', class: 'badge badge-success icon-confirm')
    else
      content_tag(:span, '✘', class: 'badge badge-important icon-reject')
    end
  end
end

app/views/application/_backend_navigation.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "Dashboard", root_path, class: "navbar-brand"
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        - if access_policy.permitted?(:scheme_management)
          = nav_item "Schemes",
                     schemes_path,
                     schemes: %w(index show new edit)
          = nav_item "Applications",
                     unconfirmed_schemes_path,
                     schemes: "unconfirmed"
          = nav_item "Feedback",
                     [:unapproved, :feedbacks],
                     "feedbacks"
          = nav_item "Csv Import",
                     [:import_form, :import_via_csv, :schemes],
                     active_top_nav: :import_via_csv
        - if access_policy.permitted?(:user_management)
          = nav_item "Users", accounts_path, "accounts"
      ul.nav.navbar-nav.pull-right
        li
          = link_to "Sign out", destroy_user_session_path, method: :delete

app/views/application/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name == :notice ? "success" : "danger"}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/application/_navigation.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse

      ul.nav.navbar-nav.pull-right
        = nav_item('Sign in', new_user_session_path)